labels:
  app: automoto.bitbucket
  team: security
  language: dotnet-core

stages:
  restore:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
    - dotnet restore --packages .nuget/packages

  build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
    - dotnet build --configuration Release --version-suffix ${ESTAFETTE_BUILD_VERSION_PATCH} --no-restore

  publish:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
    - dotnet publish src/Automoto.Bitbucket.WebService --configuration Release --runtime linux-musl-x64 --version-suffix ${ESTAFETTE_BUILD_VERSION_PATCH} --output ./publish --no-restore

  bake:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    action: build
    path: src/Automoto.Bitbucket.WebService/publish
    repositories:
    - eu.gcr.io/travix-com

  push-to-gcr-io:
    image: extensions/docker:stable
    action: push
    repositories:
    - eu.gcr.io/travix-com

